name: Run Unity Tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
  workflow_dispatch:

env:
  UNITY_MANIFEST: Packages/${{ github.event.repository.name }}/package.json
  PACKAGE_CONTENTS: ${{ github.event.repository.name }}
  SCRIPTS_DIR: .github/scripts

jobs:
  create-unity-project:
    name: Create Unity Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir $PACKAGE_CONTENTS
      - run: mv -v $(git ls-tree --full-tree --name-only HEAD | grep -v '^\.') $PACKAGE_CONTENTS
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: $SCRIPTS_DIR/create_unity_project.py $PACKAGE_CONTENTS/package.json
      - uses: actions/upload-artifact@v3
        with:
          name: unity-project
          path: |
            Assets
            Packages
            $PACKAGE_CONTENTS
          retention-days: 1

  get-unity-version:
    name: Get Unity Version
    runs-on: ubuntu-latest
    container:
      image: unityci/hub:latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "UNITY_VERSION=$(unity-hub editors --releases | grep $(cat package.json | grep -oE '"unity":\s*"([^"]*)' | awk -F '"' '{print $4}'))"
      - run: echo "UNITY_VERSION=$(unity-hub editors --releases | grep $(cat package.json | grep -oE '"unity":\s*"([^"]*)' | awk -F '"' '{print $4}'))" >>GITHUB_ENV
      - run: cat $GITHUB_ENV

  edit-mode-tests:
    name: Edit Mode Tests
    runs-on: ubuntu-latest
    needs:
      - create-unity-project
      - get-unity-version
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: unity-project
      - uses: actions/cache@v3
        with:
          path: Library/
          key: unity-ci-cache
      - run: mkdir Assets
      - run: echo ${{ env.UNITY_VERSION }}
      - uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: editmode
          unityVersion: ${{ env.UNITY_VERSION }}
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateHtmlReportHistory;generateBadgeReport'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results
          path: ${{ steps.tests.outputs.artifactsPath }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Coverage results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.coveragePath }}
