name: Run Unity Tests

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
  workflow_dispatch:

env:
  UNITY_MANIFEST: Packages/${{ github.event.repository.name }}/package.json
  PACKAGE_MANIFEST: package.json
  SCRIPTS_DIR: .github/scripts

jobs:
  create-unity-project:
    name: Create Unity Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - run: $SCRIPTS_DIR/create_unity_project.sh
      - uses: actions/upload-artifact@v3
        with:
          name: unity-project
          path: |
            Assets/
            Packages/
          retention-days: 1
  get-unity-version:
    name: Get Unity Version
    runs-on: ubuntu-latest
    container:
      image: unityci/hub:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - run: $SCRIPTS_DIR/get_min_unity_version.sh
    outputs:
      unity-version: MIN_UNITY_VERSION
  edit-mode-tests:
    runs-on: ubuntu-latest
    needs:
      - create-unity-project
      - get-unity-version
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: unity-project
      - uses: actions/cache@v3
        with:
          path: Library/
          key: unity-ci-cache
      - uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          testMode: editmode
          unityVersion: ${{ steps.get-unity-version.outputs.unity-version }}
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateHtmlReportHistory;generateBadgeReport'
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Test results
          path: ${{ steps.tests.outputs.artifactsPath }}
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Coverage results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.coveragePath }}
